# Generated by Django 5.2 on 2025-05-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_image",
            field=models.CharField(
                default="https://www.mountaineers.org/locations-lodges/kitsap-branch/committees/kitsap-climbing-committee/course-templates/intermediate-climbing-course/intermediate-climbing-course-kitsap-2017/@@images/fe6a30f4-8b31-4514-886b-a068836f7a39.jpeg",
                max_length=500,
            ),
        ),
    ]
