# Generated by Django 5.2 on 2025-05-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_lesson_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
