# Generated by Django 5.2 on 2025-05-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_remove_activity_activity_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("question", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="activity_images/"
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        blank=True, null=True, upload_to="activity_audio/"
                    ),
                ),
                ("answer", models.CharField(max_length=255)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_items",
                        to="course.activity",
                    ),
                ),
            ],
        ),
    ]
