# Generated by Django 5.2 on 2025-05-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_activityitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityitem",
            name="answer",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="activityitem",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
