# Generated by Django 5.2 on 2025-05-12 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_alter_activityitem_answer_alter_activityitem_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("question", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="activity_images/"
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        blank=True, null=True, upload_to="activity_audio/"
                    ),
                ),
                ("answer", models.CharField(max_length=100)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="course.activity",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ActivityItem",
        ),
    ]
