# Generated by Django 5.2 on 2025-05-12 14:51

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0009_item_delete_activityitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="course_title",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_image",
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=course.models.course_media_path
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=course.models.course_media_path
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to=course.models.course_media_path
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=course.models.course_media_path
            ),
        ),
    ]
