# Generated by Django 5.2 on 2025-05-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0010_rename_course_title_course_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="{courses.id}/"),
        ),
        migrations.AlterField(
            model_name="course",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="{courses.id}/"),
        ),
    ]
