# Generated by Django 5.2 on 2025-05-12 15:12

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0011_alter_course_image_alter_course_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=course.models.course_media_path
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=course.models.course_media_path
            ),
        ),
    ]
