# Generated by Django 5.2 on 2025-05-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0012_alter_course_image_alter_course_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="courses/{id}"),
        ),
    ]
