# Generated by Django 5.2 on 2025-05-12 15:33

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0013_alter_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=course.models.course_media_path
            ),
        ),
    ]
