# Generated by Django 5.2 on 2025-05-12 15:37

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0014_alter_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to=course.models.item_media_path
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=course.models.item_media_path
            ),
        ),
    ]
