# Generated by Django 5.2.1 on 2025-05-14 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0017_activity_completed_enrollment_progress_and_more"),
        ("user", "0006_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentactivity",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.profile"
            ),
        ),
    ]
