# Generated by Django 5.2 on 2025-05-14 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0018_alter_studentactivity_student"),
        ("user", "0006_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.profile"
            ),
        ),
    ]
