# Generated by Django 5.2 on 2025-05-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0020_alter_studentactivity_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentitem",
            name="next_revision",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="studentitem",
            name="revision_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="studentitem",
            name="update_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
