# Generated by Django 5.2 on 2025-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0021_studentitem_next_revision_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentitem",
            old_name="update_at",
            new_name="revision_at",
        ),
        migrations.RemoveField(
            model_name="studentitem",
            name="revision_number",
        ),
        migrations.AddField(
            model_name="studentitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentitem",
            name="next_revision",
            field=models.IntegerField(default=0),
        ),
    ]
