# Generated by Django 5.2 on 2025-05-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0022_rename_update_at_studentitem_revision_at_and_more"),
        ("user", "0006_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="user.profile",
            ),
        ),
    ]
