# Generated by Django 5.2 on 2025-05-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0023_course_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentitem",
            name="next_revision",
        ),
        migrations.AddField(
            model_name="studentitem",
            name="next_1",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="studentitem",
            name="next_2",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="studentitem",
            name="revisions",
            field=models.SmallIntegerField(default=0),
        ),
    ]
