# Generated by Django 5.2 on 2025-05-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0024_remove_studentitem_next_revision_studentitem_next_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentitem",
            name="next_2",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
