# Generated by Django 5.2 on 2025-05-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0025_alter_studentitem_next_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcourse",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
