# Generated by Django 5.2 on 2025-05-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0026_studentcourse_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("exercise", "Exercise"),
                    ("video", "Video"),
                    ("html", "Content"),
                ],
                default="exercise",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="html_content",
            field=models.TextField(
                blank=True,
                help_text="Enter formatted content using the rich text editor",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="video_embed_code",
            field=models.TextField(
                blank=True, help_text="Paste YouTube/Vimeo embed code here", null=True
            ),
        ),
    ]
