# Generated by Django 5.2 on 2025-05-18 09:52

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0027_alter_activity_options_activity_activity_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="html_content",
            field=tinymce.models.HTMLField(blank=True, default="", null=True),
        ),
    ]
