# Generated by Django 5.2 on 2025-05-18 10:10

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0028_alter_activity_html_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=tinymce.models.HTMLField(blank=True, default="", null=True),
        ),
    ]
