# Generated by Django 5.2 on 2025-05-18 14:11

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0029_alter_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default/course-default.png",
                null=True,
                upload_to=course.models.course_media_path,
            ),
        ),
    ]
