# Generated by Django 5.2 on 2025-05-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0031_alter_course_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentitem",
            old_name="next_1",
            new_name="next",
        ),
        migrations.RemoveField(
            model_name="studentitem",
            name="next_2",
        ),
    ]
