# Generated by Django 5.2 on 2025-05-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0032_rename_next_1_studentitem_next_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentitem",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
