# Generated by Django 5.2 on 2025-05-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0033_studentitem_is_correct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentitem",
            name="revision_at",
        ),
    ]
