# Generated by Django 5.2.1 on 2025-05-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0034_remove_studentitem_revision_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentitem",
            name="next",
        ),
        migrations.AddField(
            model_name="studentitem",
            name="next_1",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentitem",
            name="next_2",
            field=models.IntegerField(default=1),
        ),
    ]
