# Generated by Django 5.2.1 on 2025-05-31 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0035_remove_studentitem_next_studentitem_next_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentitem",
            old_name="is_correct",
            new_name="is_revised",
        ),
    ]
