# Generated by Django 5.2.1 on 2025-05-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0036_rename_is_correct_studentitem_is_revised"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentitem",
            old_name="revisions",
            new_name="successes",
        ),
        migrations.RemoveField(
            model_name="studentitem",
            name="is_revised",
        ),
        migrations.RemoveField(
            model_name="studentitem",
            name="next_1",
        ),
        migrations.RemoveField(
            model_name="studentitem",
            name="next_2",
        ),
    ]
