# Generated by Django 5.2.1 on 2025-06-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0037_rename_revisions_studentitem_successes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="completed",
        ),
        migrations.AddField(
            model_name="studentactivity",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="studentactivity",
            name="progress",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
