# Generated by Django 5.2.1 on 2025-06-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0038_remove_activity_completed_studentactivity_completed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentcourse",
            name="progress",
        ),
    ]
