# Generated by Django 5.2.1 on 2025-06-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0039_remove_studentcourse_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentitem",
            name="next_1",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="studentitem",
            name="next_2",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="studentitem",
            name="to_revise",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
