# Generated by Django 5.2.1 on 2025-06-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0040_studentitem_next_1_studentitem_next_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentitem",
            name="to_revise",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
