# Generated by Django 5.2.1 on 2025-06-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0041_alter_studentitem_to_revise"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentitem",
            name="revise_status",
            field=models.BooleanField(default=False),
        ),
    ]
