# Generated by Django 5.2.1 on 2025-06-08 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0042_studentitem_revise_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentitem",
            old_name="to_revise",
            new_name="next_revision",
        ),
        migrations.RenameField(
            model_name="studentitem",
            old_name="revise_status",
            new_name="skip_revision",
        ),
    ]
