# Generated by Django 5.2.1 on 2025-06-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0043_rename_to_revise_studentitem_next_revision_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentitem",
            old_name="next_revision",
            new_name="revise_at",
        ),
    ]
