# Generated by Django 5.2.1 on 2025-06-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0044_rename_next_revision_studentitem_revise_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentitem",
            name="skip_revision",
        ),
        migrations.AddField(
            model_name="studentitem",
            name="continue_revision",
            field=models.BooleanField(default=True),
        ),
    ]
