# Generated by Django 5.2.1 on 2025-06-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0045_remove_studentitem_skip_revision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Is this course published?"
            ),
        ),
    ]
