# Generated by Django 5.2.1 on 2025-06-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0046_course_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
