# Generated by Django 5.2.4 on 2025-08-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0049_alter_item_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload a PDF file', null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('exercise', 'Exercise'), ('video', 'Video'), ('html', 'Content'), ('pdf', 'PDF')], default='exercise', max_length=10),
        ),
    ]
