# Generated by Django 5.2.4 on 2025-08-18 17:39

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0050_activity_pdf_file_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('exercise', 'Exercise'), ('video', 'Video'), ('html', 'Content'), ('pdf', 'PDF')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload a PDF file', null=True, upload_to=course.models.pdf_media_path),
        ),
        migrations.AlterField(
            model_name='activity',
            name='video_embed_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
