# Generated by Django 5.2.4 on 2025-08-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0051_alter_activity_options_alter_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='answer1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='answer2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='answer3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='answer4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
