# Generated by Django 5.2.4 on 2025-08-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0052_item_answer1_item_answer2_item_answer3_item_answer4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('card', 'Flash Card'), ('mc', 'Multiple Choice'), ('blank', 'Fill in the Blank'), ('sentence', 'Sentence')], default='card', max_length=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('exercise', 'Exercise'), ('video', 'Video'), ('html', 'Content'), ('pdf', 'PDF')], max_length=10),
        ),
    ]
