# Generated by Django 5.2.4 on 2025-08-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0053_item_item_type_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('card', 'Flash Card'), ('mc', 'Multiple Choice'), ('blank', 'Fill in the Blank')], default='card', max_length=10),
        ),
    ]
