# Generated by Django 5.2.4 on 2025-08-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0054_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('card', 'Flash Card'), ('mc', 'Multiple Choice')], default='card', max_length=10),
        ),
    ]
