# Generated by Django 5.2.4 on 2025-08-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0055_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='audio_play',
            field=models.CharField(blank=True, choices=[('start', 'Play at Start'), ('end', 'Play at End'), ('both', 'Play at Both')], default='start', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('card', 'Flash Card'), ('mc', 'Multiple Choice'), ('blank', 'Fill in the Blank')], default='card', max_length=10),
        ),
    ]
