# Generated by Django 5.2.4 on 2025-08-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0056_item_audio_play_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='number_answers',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
