# Generated by Django 5.2.4 on 2025-09-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0057_item_number_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
