# Generated by Django 5.2.4 on 2025-09-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0059_alter_item_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
