# Generated by Django 5.2.4 on 2025-09-05 22:12

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0060_alter_item_item_category'),
    ]


