# Generated by Django 5.2.4 on 2025-09-09 19:22

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0061_activity_audio_file_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload an MP3 file', null=True, upload_to=course.models.audio_media_path),
        ),
        migrations.AddField(
            model_name='activity',
            name='script',
            field=models.JSONField(blank=True, default=list, help_text='Timestamps for audio captions in JSON format', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('exercise', 'Exercise'), ('video', 'Video'), ('html', 'Content'), ('pdf', 'PDF'), ('reading', 'Reading')], max_length=10),
        ),
    ]
