# Generated by Django 5.2.4 on 2025-12-31 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0062_activity_audio_file_activity_script_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='script',
        ),
    ]
