# Generated by Django 5.2.4 on 2026-01-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0063_remove_activity_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
