# Generated by Django 5.1.1 on 2025-09-22 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
        ("user", "0012_remove_profile_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("successes", models.SmallIntegerField(default=0)),
                ("is_master", models.BooleanField(default=False)),
                ("next_1", models.IntegerField(default=1)),
                ("next_2", models.IntegerField(default=1)),
                ("revise_at", models.DateTimeField(blank=True, null=True)),
                ("continue_revision", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_words",
                        to="user.profile",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.dictionaryitem",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "word")},
            },
        ),
    ]
