# Generated by Django 5.1.1 on 2025-09-25 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0002_studentword"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentword",
            name="dictionary_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dictionary.dictionaryitem",
            ),
        ),
        migrations.AddField(
            model_name="studentword",
            name="meaning",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentword",
            name="word",
            field=models.CharField(max_length=255),
        ),
    ]
