# Generated by Django 5.2 on 2025-05-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_profile_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
