# Generated by Django 5.2 on 2025-05-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_profile_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
    ]
