# Generated by Django 5.2.1 on 2025-05-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_rename_first_name_profile_name_remove_profile_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="school",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
