# Generated by Django 5.2.1 on 2025-05-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_profile_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
