# Generated by Django 5.2 on 2025-05-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="school",
        ),
    ]
