# Generated by Django 5.2 on 2025-05-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_profile_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_active",
        ),
    ]
