# Generated by Django 5.2.1 on 2025-05-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_remove_profile_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="default/dummy.png",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
