# Generated by Django 5.2.1 on 2025-05-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/dummy.png",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
