# Generated by Django 5.2.1 on 2025-05-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="role",
        ),
    ]
